### ISSUE TITLE
Plugin manager is missing

### ISSUE THREAD

**Issue by bontempo** [NightRi-se/notepad-plus-plus#10]
### Description of the Issue
The plugin manager is missing in the menu. This is important to add "features", like file comparison.

### Steps to Reproduce the Issue
1. Install Notepad++ from Store
2. Open Notepad++
3. Open menu "Plugins"; the option "Plugin manager" is missing

**Comment by jakevis** [comment]
thanks for the report - ill investigate. This package wasn't assembled using the installer - it was the raw exe and config files.

**Comment by jakevis** [comment]
Ok - this is assosiated with this:
https://notepad-plus-plus.org/community/topic/12483/new-version-of-plugin-manager-for-testing/3

and this:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2430

I will see about including the new plugin manager from https://github.com/bruderstein/nppPluginManager/releases in this next release

**Comment by JoeMSFT** [comment]
Is there a workaround for installing the PluginManager manually?   I started fiddling with it for a quick second -- but it looks like I will have to modify the default permissions to copy the PluginManager.dll into the WindowsApp folder.  Or am I missing something obvious?

**Comment by jakevis** [comment]
the zero byte allowAppDataPlugins.xml file needs to be added to the windowsapp folder to allow plugins to load from %appdata%... that will be fixed in #8 (once its published).

**Comment by jakevis** [comment]
I will also say... if you really want this now... and are not on win10s - you can install manully. Just install the cert into machine trusted root, then install the appx, then remove the cert (or leave it if you trust me ;) )

**Comment by jakevis** [comment]
@joemsft - 7.55.2.0 is now being pushed as an update. If you update, that xml file will be there and you can add 64bit plug-ins from appdata

**Comment by jakevis** [comment]
@bontempo and @JoeMSFT  - unfortunaly I cant include plugin manger at this time... the gpup.exe program that is included and needed to remove plugins, requires admin privileges.. and that is not allowed in the store. 

https://github.com/bruderstein/nppPluginManager/issues/35

Ill see if there is a way of fixing this, or if I can make an easy to install the plugin manager in %appdata%

**Comment by chcg** [comment]
@jakevis Did you add allowAppDataPlugins.xml to do the plugin installation under %appdata%? This way gpup.exe is probably not necessary at all.

**Comment by jakevis** [comment]
@chcg - so allowAppDataPlugins.xml is included in the installation directory (that ends up being C:\Program Files\WindowsApps\NightRise.NotepadWrapped_7.56.1.0_x64__bahp16nyyek9m\). On first installation %appdata%/notepad++ includes nothing and is created. New plugins do install correctly into appdata, its just that gpup cant run to remove anything.... I end up in a loop on every app start, with plugin manager requesting to restart notepad++ to remove the pending plugins

**Comment by bontempo** [comment]
@jakevis - I tried to uninstall/reinstall, but the %appdata%\notepad++ was not created, even running as an administrator. Additional question: maybe this folder shouldn't be in %programdata%, rather %appdata%? Or it's because the Windows Store structure?

**Comment by jakevis** [comment]
hi @bontempo - so the situations in what notepad++ creates  %appdata%\notepad++ seem to be strange... I have it on my machine (C:\Users\visse\AppData\Roaming\notepad++), but it doesn't seem to always create it (I think it is only created when settings that need to be saved there are).

So side issue with all this that I found in testing last week. On Windows 10S - if the DLL (plugin) is not distributed via the appstore (and signed as such in the manifest), it will not load (and notepad++ will fail to open, with a critical event in the event log created). So as such I think ill need to kill this request anyway.. I will just include some of the more popular plugin's pre-installed. [win 10 pro ect all work as expected, loading plugins from appdata if the folders are created appropriately]

**Comment by jakevis** [comment]
I cant include it, and have it work on win10s.. so closing this, and we should focus on #19

**Comment by hkusulja** [comment]
Yeah, but Windows 10S is limited on this.
I believe this should also be done, for other Windows 10 (Home) and Pro and Enterprise users..
