### ISSUE TITLE
Support Additional filestypes

### ISSUE THREAD

**Issue by jakevis** [NightRi-se/notepad-plus-plus#18]
need to add .GP

**Comment by jakevis** [comment]
also adding .gp and .ts and .scss

**Comment by abcarterblue** [comment]
Could you add files commonly used for Crystallography. It appears to be trivial so I haven't attempted to make changes myself.  .cif  .cif_od  .ins  .res  .lst  .hkl

In case this helps:
  

    <uap:FileType>.cif</uap:FileType>
    <uap:FileType>.cif_od</uap:FileType>
    <uap:FileType>.ins</uap:FileType>
    <uap:FileType>.res</uap:FileType>
    <uap:FileType>.lst</uap:FileType>
    <uap:FileType>.hkl</uap:FileType>[co


Thanks for the great work.

**Comment by jakevis** [comment]
Thanks for list @abcarterblue 👍 Just added these to the manifest now. I will aim to push this to certification in the next 24->48 hours.

**Comment by kristian-b** [comment]
.yml would be also nice.

**Comment by jakevis** [comment]
@kristian-b  - added.

Ill try and get this pushed to the MS Store tonight.

Cheers,

Jake

**Comment by kristian-b** [comment]
Thank you very much!

**Comment by jakevis** [comment]
Sorry got busy with the day job. I just published a release now. It should show up in the store in the next 2-3 days. In the mean time, you can side load using the signed appx

**Comment by jakevis** [comment]
Closing for now - feel free to create a new issue with more extension requests if need be
