### ISSUE TITLE
Plugins to Include by default

### ISSUE THREAD

**Issue by jakevis** [NightRi-se/notepad-plus-plus#19]
In lue of being able to support #10 .. i will look at including some plugins by default.

**Comment by jakevis** [comment]
Request from app feedback: MarkdownViewer++

**Comment by notNSANE** [comment]
Compare files! https://sourceforge.net/projects/npp-plugins/files/ComparePlugin/

**Comment by jakevis** [comment]
@notnsane compare is now included (pushing to the store now). Also included MarkdownViewer++ in this release

**Comment by chcg** [comment]
Latest compare plugin version is:
https://github.com/pnedev/compare-plugin/releases/tag/v2.0.0

**Comment by jakevis** [comment]
thanks @chcg - im fairly certain that's the version I included..
![image](https://user-images.githubusercontent.com/10895705/39888133-cf5bdd3e-5448-11e8-9c29-bcb8d6ec5067.png)

**Comment by fubar-coder** [comment]
I have a crazy idea: What about using the plugin support from the store?

**Comment by jakevis** [comment]
@fubar-coder love the idea - but as far as I can tell addon support seams to be more limited to licensing… Im not sure it can deploy a DLL to a specified location within the package... https://docs.microsoft.com/en-us/windows/uwp/monetize/create-an-add-on

Ill ask around and do some more searches to see if there is a supported way of doing this (also since this is a centennial app, I think i would need to create a UWP extension to make this work)

**Comment by jakevis** [comment]
So this just came out https://notepad-plus-plus.org/features/plugin-admin.html
There are many *many* *MANY* issues with it, it seems... notably the requirment for the updater, changing location of the addins, and the fact that the portable np++ instance doesnt support it (and this is based off that). I am tracking this in #36, will remove existing default plugins in the next release and try and get this the plugin admin system working

Note... it will probably never work with win10s...
