### ISSUE TITLE
Command line activation with arguments

### ISSUE THREAD

**Issue by fubar-coder** [NightRi-se/notepad-plus-plus#20]
### Description of the Issue

I'm currently unable to start the app from the command line with arguments. Starting without arguments works, by invoking `explorer "shell:appsFolder\NightRise.NotepadWrapped_bahp16nyyek9m!NotepadWrapped"`.

### Steps to Reproduce the Issue

1. Open cmd.exe
2. Enter notepad++.exe

### Expected Behavior

Notepad++ should start

### Actual Behavior

Notepad++ not starting

### Information

There is more information about this feature in this MSDN blog post:

https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/#JqkvS2MrxTAjyhE1.97

**Comment by jakevis** [comment]
thanks for the report @fubar-coder 

it looks like i should be able to include that in the manifest... and we can see if that will correct the behavior. This is a centennial app, not a UWP app through.. so sometimes it doesn't work as expected. 
Give me a few days / week (or if you can work it out, ill totaly take a pull request).

Cheers,

Jake

**Comment by jakevis** [comment]
@fubar-coder got this one working. Publishing to the store now

**Comment by jakevis** [comment]
The update is now visible in the store and should have updated client installs

**Comment by fubar-coder** [comment]
Thank you, works as expected 👍
