### ISSUE TITLE
Unable to write review on Microsoft Store

### ISSUE THREAD

**Issue by divenex** [NightRi-se/notepad-plus-plus#32]
The Microsoft Store won't let me write a review of this (very useful) fork of Notepad++ (v7.5.9). 

The Store page for this app writes at the top, next to the round blue button with the arrow, "This product is installed", and I can confirm that it is installed and it works. I can also confirm that I the desktop version of Notepad++ is **not** installed.

But in the "Review" tab the page states "Rate and review this product on the device it's installed on" which is, of course, the same PC! 

This only happens with this app and not with the many other Store apps I have installed. I am not sure this is a bug with Notepad++ or the Microsoft Store.

For this reason, I could not write a positive review yet... But many thanks for bringing the excellent Notepad++ to the Store!

**Comment by jakevis** [comment]
@divenex Thanks for letting me know 👍  - I just put a feedback item in with Microsoft, see if they can work out why.

And thanks for the positive feedback here 🥇
