### ISSUE TITLE
Can't Run command in Win10

### ISSUE THREAD

**Issue by cfgbd** [NightRi-se/notepad-plus-plus#39]
I installed (unofficial)notepad++ from Microsoft Store, and when I try to use Run->Run...(short cut F5), it just show a dialog, displaying message "Disabled due to Store Policies".
   What's the matter? Does it means in (Microsoft) Store Policies, this App can't support command line tools? Or due to my system storage policies, this App can't create an runnable plugin?

**Comment by cfgbd** [comment]
And btw, is it a bug?

**Comment by jakevis** [comment]
Sorry @cfgbd missed this one. The microsoft store policy's prevent cli tools (wdac policys prevent it.. And hence 10s can't use it).
