### ISSUE TITLE
Publish 7.55.2.0 to Store

### ISSUE THREAD

**Issue by jakevis** [NightRi-se/notepad-plus-plus#8]

**Comment by jakevis** [comment]
This is ongoing now
![image](https://user-images.githubusercontent.com/10895705/37438840-241500d0-27b2-11e8-9d10-d0b41288ac49.png)

**Comment by jakevis** [comment]
![screenshot_2018-03-15-07-45-54](https://user-images.githubusercontent.com/10895705/37470607-19da4f9e-2825-11e8-9171-6ea5e6c25d9b.png)
First attempt rejected (but all this should work)... Removing claims and resubmitted. Will need to test further.

**Comment by jakevis** [comment]
It's now published. Packages available and the store is in progress.

**Comment by 93ben** [comment]
Hi why are you using registered trademarks? https://www.facebook.com/Notepad.plus.plus/posts/1791437124241945

**Comment by jakevis** [comment]
@bgollow if there is an active trademark ill happily rename it. Just send me the link to TESS, or a trademark database that shows its active. In fact in the latest update it has a new store logo and store name anyway "(unofficial) Notepad++"

Also remember that the name notepad is not trade markable. And the current store logo, is the logo that is on the icon, that is in the GPL repo. So either way... I think this is all a BS mess.

The thread on this one is here.. https://notepad-plus-plus.org/community/topic/14734/notepad-uwp-package-in-windows-store-almost-there/43; along with my offer to transfer this repo, and published application to the team.

**Comment by jakevis** [comment]
also thanks for the facebook link... i already commented on that thread on twitter.. didn't see the facebook one
