### ISSUE TITLE
Context menu option

### ISSUE THREAD

**Issue by MahdiGhiasi** [NightRi-se/notepad-plus-plus#9]
### Description of the Issue
"Open in Notepad++" option is missing from file explorer context menu

### Steps to Reproduce the Issue

1. Install Notepad++ from Store
2. Notice that the option is missing when you right click on files via file explorer

### Notes

I'm not sure if that's possible at all with Centennial apps, but if it is, it would be a welcome change.

**Comment by jakevis** [comment]
@MahdiGhiasi - so in the release that is being certified by Microsoft now - file types will be "associated". So Open With will start to work. 

https://github.com/NightRi-se/notepad-plus-plus/wiki/Assosiated-File-Type

I will need to look at if there is a possibility to add the "edit with notepad++".. there might be something in the manifest or registery that we can set

**Comment by jakevis** [comment]
closing this one - mostly a dup of #21 - i cant work out how to make it happen, and i cant do it via registry. Although commandline calls now work, so it might be possible to add localy.
